CREATE TYPE "LogoPosition" AS ENUM ('TOP_LEFT', 'TOP_RIGHT', 'BOTTOM_LEFT', 'BOTTOM_RIGHT');

ALTER TABLE "Episode" ADD COLUMN "logoOnIntro" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Episode" ADD COLUMN "logoOnOutro" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Episode" ADD COLUMN "logoPosition" "LogoPosition" NOT NULL DEFAULT 'BOTTOM_RIGHT';
